// 500+ English words for daily word game
const WORD_BANK = [
// 5-letter words (Easy)
{word:'BRAVE',type:'adjective',def:'Cesur, yiğit',ex:'She was brave enough to speak.',tr:'Cesur'},
{word:'FOCUS',type:'verb',def:'Odaklanmak',ex:'Focus on your studies.',tr:'Odak'},
{word:'GRASP',type:'verb',def:'Kavramak, anlamak',ex:'Grasp the concept.',tr:'Kavramak'},
{word:'PRIDE',type:'noun',def:'Gurur duyma',ex:'She felt great pride.',tr:'Gurur'},
{word:'SHARP',type:'adj',def:'Keskin, zeki',ex:'A sharp mind.',tr:'Keskin'},
{word:'BLEND',type:'verb',def:'Karıştırmak',ex:'Blend the ingredients.',tr:'Karışım'},
{word:'CRAFT',type:'noun',def:'El sanatı',ex:'She crafted a letter.',tr:'Zanaat'},
{word:'DREAM',type:'noun',def:'Rüya, hayal',ex:'Never stop dreaming.',tr:'Rüya'},
{word:'EAGER',type:'adj',def:'Hevesli',ex:'Eager to learn.',tr:'İstekli'},
{word:'FLAME',type:'noun',def:'Alev',ex:'The flame burned bright.',tr:'Alev'},
{word:'GRACE',type:'noun',def:'Zarafet',ex:'She moved with grace.',tr:'Zarafet'},
{word:'HAPPY',type:'adj',def:'Mutlu',ex:'Learning makes me happy.',tr:'Mutlu'},
{word:'IDEAL',type:'adj',def:'Mükemmel',ex:'The ideal time.',tr:'İdeal'},
{word:'JUDGE',type:'verb',def:'Yargılamak',ex:'Don\'t judge others.',tr:'Yargılamak'},
{word:'KNACK',type:'noun',def:'Yetenek',ex:'A knack for languages.',tr:'Maharet'},
{word:'LIGHT',type:'noun',def:'Işık',ex:'The light of knowledge.',tr:'Işık'},
{word:'MAGIC',type:'noun',def:'Sihir',ex:'Magic in every word.',tr:'Sihir'},
{word:'NERVE',type:'noun',def:'Cesaret, sinir',ex:'It takes nerve.',tr:'Cesaret'},
{word:'OCEAN',type:'noun',def:'Okyanus',ex:'An ocean of chances.',tr:'Okyanus'},
{word:'PEACE',type:'noun',def:'Barış, huzur',ex:'Peace of mind.',tr:'Barış'},
{word:'QUICK',type:'adj',def:'Hızlı, çabuk',ex:'A quick response.',tr:'Hızlı'},
{word:'REACH',type:'verb',def:'Ulaşmak',ex:'Reach your goals.',tr:'Ulaşmak'},
{word:'SMILE',type:'noun',def:'Gülümseme',ex:'A warm smile.',tr:'Gülümseme'},
{word:'TRUST',type:'noun',def:'Güven',ex:'Build trust slowly.',tr:'Güven'},
{word:'UNITY',type:'noun',def:'Birlik',ex:'Unity is strength.',tr:'Birlik'},
{word:'VALUE',type:'noun',def:'Değer',ex:'Know your value.',tr:'Değer'},
{word:'WORTH',type:'noun',def:'Değer, kıymet',ex:'Worth the effort.',tr:'Kıymet'},
{word:'YOUTH',type:'noun',def:'Gençlik',ex:'The youth of today.',tr:'Gençlik'},
{word:'AGREE',type:'verb',def:'Aynı fikirde olmak',ex:'I agree with you.',tr:'Kabul etmek'},
{word:'BASIC',type:'adj',def:'Temel',ex:'Basic knowledge.',tr:'Temel'},
{word:'CHASE',type:'verb',def:'Kovalamak',ex:'Chase your dreams.',tr:'Kovalamak'},
{word:'DOUBT',type:'noun',def:'Şüphe',ex:'No room for doubt.',tr:'Şüphe'},
{word:'EMPTY',type:'adj',def:'Boş',ex:'An empty room.',tr:'Boş'},
{word:'FAITH',type:'noun',def:'İnanç',ex:'Have faith.',tr:'İnanç'},
{word:'GIANT',type:'noun',def:'Dev',ex:'A tech giant.',tr:'Dev'},
{word:'HEART',type:'noun',def:'Kalp',ex:'Follow your heart.',tr:'Kalp'},
{word:'IMAGE',type:'noun',def:'Görüntü',ex:'A clear image.',tr:'İmaj'},
{word:'JOINT',type:'adj',def:'Ortak',ex:'A joint effort.',tr:'Ortak'},
{word:'KNOWN',type:'adj',def:'Bilinen',ex:'A well-known fact.',tr:'Bilinen'},
{word:'LEARN',type:'verb',def:'Öğrenmek',ex:'Learn every day.',tr:'Öğrenmek'},
{word:'MATCH',type:'noun',def:'Eşleşme, maç',ex:'A perfect match.',tr:'Eşleşme'},
{word:'NOBLE',type:'adj',def:'Asil, soylu',ex:'A noble cause.',tr:'Asil'},
{word:'ORDER',type:'noun',def:'Düzen, sipariş',ex:'Keep order.',tr:'Düzen'},
{word:'POWER',type:'noun',def:'Güç',ex:'Knowledge is power.',tr:'Güç'},
{word:'QUEEN',type:'noun',def:'Kraliçe',ex:'The queen spoke.',tr:'Kraliçe'},
{word:'RAISE',type:'verb',def:'Yükseltmek',ex:'Raise your hand.',tr:'Kaldırmak'},
{word:'SENSE',type:'noun',def:'Duyu, anlam',ex:'Make sense.',tr:'Anlam'},
{word:'TRAIN',type:'verb',def:'Eğitmek',ex:'Train daily.',tr:'Eğitmek'},
{word:'UPPER',type:'adj',def:'Üst',ex:'Upper level.',tr:'Üst'},
{word:'VOICE',type:'noun',def:'Ses',ex:'Raise your voice.',tr:'Ses'},
{word:'WHILE',type:'conj',def:'İken, süre',ex:'Wait a while.',tr:'Süre'},
{word:'YIELD',type:'verb',def:'Vermek, teslim olmak',ex:'Yield results.',tr:'Sonuç vermek'},
{word:'ZONAL',type:'adj',def:'Bölgesel',ex:'Zonal defense.',tr:'Bölgesel'},
{word:'ALONE',type:'adj',def:'Yalnız',ex:'You are not alone.',tr:'Yalnız'},
{word:'BIRTH',type:'noun',def:'Doğum',ex:'Date of birth.',tr:'Doğum'},
{word:'CLAIM',type:'verb',def:'İddia etmek',ex:'Claim your right.',tr:'İddia'},
{word:'DRIVE',type:'verb',def:'Sürmek',ex:'Drive carefully.',tr:'Sürmek'},
{word:'ELECT',type:'verb',def:'Seçmek',ex:'Elect a leader.',tr:'Seçmek'},
{word:'FAULT',type:'noun',def:'Hata, kusur',ex:'Not my fault.',tr:'Hata'},
{word:'GLOBE',type:'noun',def:'Dünya, küre',ex:'Around the globe.',tr:'Küre'},
{word:'HONOR',type:'noun',def:'Onur, şeref',ex:'An honor to meet.',tr:'Onur'},
{word:'ISSUE',type:'noun',def:'Sorun, konu',ex:'A key issue.',tr:'Mesele'},
{word:'JUICE',type:'noun',def:'Meyve suyu',ex:'Orange juice.',tr:'Meyve suyu'},
{word:'KNIFE',type:'noun',def:'Bıçak',ex:'A sharp knife.',tr:'Bıçak'},
{word:'LEVEL',type:'noun',def:'Seviye',ex:'Next level.',tr:'Seviye'},
{word:'MEDAL',type:'noun',def:'Madalya',ex:'Win a medal.',tr:'Madalya'},
{word:'NOISE',type:'noun',def:'Gürültü',ex:'Too much noise.',tr:'Gürültü'},
{word:'OFFER',type:'verb',def:'Teklif etmek',ex:'Offer help.',tr:'Teklif'},
{word:'PANEL',type:'noun',def:'Panel',ex:'A control panel.',tr:'Panel'},
{word:'QUOTE',type:'noun',def:'Alıntı',ex:'A famous quote.',tr:'Alıntı'},
{word:'ROUTE',type:'noun',def:'Rota, yol',ex:'The best route.',tr:'Rota'},
{word:'SCENE',type:'noun',def:'Sahne',ex:'A beautiful scene.',tr:'Sahne'},
{word:'THEME',type:'noun',def:'Tema, konu',ex:'The main theme.',tr:'Tema'},
{word:'URBAN',type:'adj',def:'Kentsel',ex:'Urban areas.',tr:'Kentsel'},
{word:'VITAL',type:'adj',def:'Hayati',ex:'Vital information.',tr:'Hayati'},
{word:'WASTE',type:'noun',def:'İsraf, atık',ex:'Don\'t waste time.',tr:'İsraf'},
{word:'EXACT',type:'adj',def:'Tam, kesin',ex:'The exact time.',tr:'Kesin'},
{word:'ADAPT',type:'verb',def:'Uyum sağlamak',ex:'Adapt to change.',tr:'Uyum'},
{word:'BELOW',type:'prep',def:'Aşağıda',ex:'Below average.',tr:'Aşağıda'},
{word:'CLEAR',type:'adj',def:'Açık, net',ex:'Clear instructions.',tr:'Açık'},
{word:'DEPTH',type:'noun',def:'Derinlik',ex:'In depth analysis.',tr:'Derinlik'},
{word:'EVENT',type:'noun',def:'Etkinlik, olay',ex:'A major event.',tr:'Etkinlik'},
{word:'FLOOR',type:'noun',def:'Zemin, kat',ex:'The first floor.',tr:'Zemin'},
{word:'GUIDE',type:'noun',def:'Rehber',ex:'A travel guide.',tr:'Rehber'},
{word:'HUMAN',type:'noun',def:'İnsan',ex:'Human nature.',tr:'İnsan'},
{word:'INPUT',type:'noun',def:'Girdi',ex:'User input.',tr:'Girdi'},
{word:'LAYER',type:'noun',def:'Katman',ex:'Add a layer.',tr:'Katman'},
{word:'MINOR',type:'adj',def:'Küçük, önemsiz',ex:'A minor issue.',tr:'Küçük'},
{word:'PITCH',type:'noun',def:'Saha, ton',ex:'A football pitch.',tr:'Saha'},
{word:'RANGE',type:'noun',def:'Aralık, menzil',ex:'Wide range.',tr:'Aralık'},
{word:'SCALE',type:'noun',def:'Ölçek',ex:'On a large scale.',tr:'Ölçek'},
{word:'SWEAR',type:'verb',def:'Yemin etmek',ex:'I swear.',tr:'Yemin'},
{word:'THICK',type:'adj',def:'Kalın',ex:'A thick book.',tr:'Kalın'},
{word:'UTTER',type:'adj',def:'Tam, mutlak',ex:'Utter silence.',tr:'Tam'},
{word:'VAPOR',type:'noun',def:'Buhar',ex:'Water vapor.',tr:'Buhar'},
{word:'WEIGH',type:'verb',def:'Tartmak',ex:'Weigh the options.',tr:'Tartmak'},
{word:'ALARM',type:'noun',def:'Alarm',ex:'Sound the alarm.',tr:'Alarm'},
{word:'BOOST',type:'verb',def:'Artırmak',ex:'Boost your skills.',tr:'Artırmak'},
{word:'CRASH',type:'verb',def:'Çarpmak',ex:'The car crashed.',tr:'Çarpmak'},
{word:'DRAFT',type:'noun',def:'Taslak',ex:'A rough draft.',tr:'Taslak'},
{word:'FIFTY',type:'noun',def:'Elli',ex:'Fifty percent.',tr:'Elli'},
{word:'GRAND',type:'adj',def:'Büyük, görkemli',ex:'A grand plan.',tr:'Görkemli'},
{word:'HOVER',type:'verb',def:'Havada durmak',ex:'Hover over it.',tr:'Süzülmek'},
{word:'INNER',type:'adj',def:'İç, dahili',ex:'Inner peace.',tr:'İç'},
{word:'JOLLY',type:'adj',def:'Neşeli',ex:'A jolly person.',tr:'Neşeli'},
{word:'LEMON',type:'noun',def:'Limon',ex:'Fresh lemon.',tr:'Limon'},
{word:'MANGO',type:'noun',def:'Mango',ex:'Tropical mango.',tr:'Mango'},
{word:'NERVE',type:'noun',def:'Sinir',ex:'Hit a nerve.',tr:'Sinir'},
{word:'OLIVE',type:'noun',def:'Zeytin',ex:'Olive oil.',tr:'Zeytin'},
{word:'PIANO',type:'noun',def:'Piyano',ex:'Play the piano.',tr:'Piyano'},
{word:'RADAR',type:'noun',def:'Radar',ex:'Under the radar.',tr:'Radar'},
{word:'SAUCE',type:'noun',def:'Sos',ex:'Tomato sauce.',tr:'Sos'},
{word:'TOWER',type:'noun',def:'Kule',ex:'A tall tower.',tr:'Kule'},
{word:'ULTRA',type:'adj',def:'Aşırı',ex:'Ultra fast.',tr:'Aşırı'},
{word:'VIGOR',type:'noun',def:'Enerji, güç',ex:'Full of vigor.',tr:'Enerji'},
{word:'WHALE',type:'noun',def:'Balina',ex:'A blue whale.',tr:'Balina'},
{word:'ANGEL',type:'noun',def:'Melek',ex:'Like an angel.',tr:'Melek'},
{word:'BONUS',type:'noun',def:'Bonus, prim',ex:'A bonus point.',tr:'Bonus'},
{word:'CANDY',type:'noun',def:'Şeker',ex:'Sweet candy.',tr:'Tatlı'},
{word:'DANCE',type:'verb',def:'Dans etmek',ex:'Let\'s dance.',tr:'Dans'},
{word:'EARTH',type:'noun',def:'Dünya, toprak',ex:'Planet Earth.',tr:'Dünya'},
{word:'FANCY',type:'adj',def:'Süslü, lüks',ex:'A fancy dress.',tr:'Süslü'},
{word:'GHOST',type:'noun',def:'Hayalet',ex:'A ghost story.',tr:'Hayalet'},
{word:'HARSH',type:'adj',def:'Sert, kaba',ex:'Harsh words.',tr:'Sert'},
{word:'IVORY',type:'noun',def:'Fildişi',ex:'Ivory tower.',tr:'Fildişi'},
{word:'JELLY',type:'noun',def:'Jöle',ex:'Strawberry jelly.',tr:'Jöle'},
{word:'LUNCH',type:'noun',def:'Öğle yemeği',ex:'Time for lunch.',tr:'Öğle yemeği'},
{word:'MONTH',type:'noun',def:'Ay (takvim)',ex:'Next month.',tr:'Ay'},
{word:'NIGHT',type:'noun',def:'Gece',ex:'Good night.',tr:'Gece'},
{word:'OPERA',type:'noun',def:'Opera',ex:'At the opera.',tr:'Opera'},
{word:'PATCH',type:'noun',def:'Yama',ex:'A software patch.',tr:'Yama'},
{word:'ROCKY',type:'adj',def:'Kayalık',ex:'A rocky road.',tr:'Kayalık'},
{word:'SPINE',type:'noun',def:'Omurga',ex:'A strong spine.',tr:'Omurga'},
{word:'TREND',type:'noun',def:'Eğilim, trend',ex:'The latest trend.',tr:'Trend'},
{word:'UPSET',type:'adj',def:'Üzgün, kızgın',ex:'Don\'t be upset.',tr:'Üzgün'},
{word:'VOTER',type:'noun',def:'Seçmen',ex:'Every voter matters.',tr:'Seçmen'},
{word:'WRITE',type:'verb',def:'Yazmak',ex:'Write a letter.',tr:'Yazmak'},
{word:'YACHT',type:'noun',def:'Yat',ex:'A luxury yacht.',tr:'Yat'},
{word:'ZEBRA',type:'noun',def:'Zebra',ex:'Black and white.',tr:'Zebra'},
{word:'APPLE',type:'noun',def:'Elma',ex:'An apple a day.',tr:'Elma'},
{word:'BEACH',type:'noun',def:'Plaj, sahil',ex:'At the beach.',tr:'Plaj'},
{word:'CHESS',type:'noun',def:'Satranç',ex:'Play chess.',tr:'Satranç'},
{word:'DELAY',type:'noun',def:'Gecikme',ex:'Without delay.',tr:'Gecikme'},
{word:'ESSAY',type:'noun',def:'Deneme, makale',ex:'Write an essay.',tr:'Deneme'},
{word:'FRESH',type:'adj',def:'Taze',ex:'Fresh air.',tr:'Taze'},
{word:'GREEN',type:'adj',def:'Yeşil',ex:'Green forest.',tr:'Yeşil'},
{word:'HONEY',type:'noun',def:'Bal',ex:'Sweet honey.',tr:'Bal'},
{word:'LARGE',type:'adj',def:'Büyük, geniş',ex:'A large room.',tr:'Büyük'},
{word:'MAYOR',type:'noun',def:'Belediye başkanı',ex:'The new mayor.',tr:'Başkan'},
{word:'NOVEL',type:'noun',def:'Roman',ex:'A great novel.',tr:'Roman'},
{word:'ORBIT',type:'noun',def:'Yörünge',ex:'In orbit.',tr:'Yörünge'},
{word:'PLANT',type:'noun',def:'Bitki',ex:'A green plant.',tr:'Bitki'},
{word:'REBEL',type:'noun',def:'Asi, isyancı',ex:'A young rebel.',tr:'Asi'},
{word:'SKILL',type:'noun',def:'Beceri',ex:'New skill.',tr:'Beceri'},
{word:'TOTAL',type:'adj',def:'Toplam',ex:'Total score.',tr:'Toplam'},
{word:'VIRUS',type:'noun',def:'Virüs',ex:'Computer virus.',tr:'Virüs'},
{word:'WATCH',type:'verb',def:'İzlemek',ex:'Watch and learn.',tr:'İzlemek'},
{word:'ARROW',type:'noun',def:'Ok',ex:'Follow the arrow.',tr:'Ok'},
{word:'BLOCK',type:'noun',def:'Blok',ex:'A road block.',tr:'Blok'},
{word:'CLOUD',type:'noun',def:'Bulut',ex:'In the cloud.',tr:'Bulut'},
{word:'DRIFT',type:'verb',def:'Sürüklenmek',ex:'Don\'t drift away.',tr:'Sürüklenme'},
{word:'EQUAL',type:'adj',def:'Eşit',ex:'Equal rights.',tr:'Eşit'},
{word:'FIBER',type:'noun',def:'Lif, fiber',ex:'Dietary fiber.',tr:'Lif'},
{word:'GRAIN',type:'noun',def:'Tahıl, tane',ex:'A grain of sand.',tr:'Tane'},
{word:'HUMID',type:'adj',def:'Nemli',ex:'Hot and humid.',tr:'Nemli'},
{word:'JOINT',type:'noun',def:'Eklem',ex:'Joint pain.',tr:'Eklem'},
{word:'LASER',type:'noun',def:'Lazer',ex:'Laser beam.',tr:'Lazer'},
{word:'MAPLE',type:'noun',def:'Akçaağaç',ex:'Maple syrup.',tr:'Akçaağaç'},
{word:'OASIS',type:'noun',def:'Vaha',ex:'An oasis of calm.',tr:'Vaha'},
{word:'PHASE',type:'noun',def:'Aşama, faz',ex:'Next phase.',tr:'Aşama'},
{word:'ROYAL',type:'adj',def:'Kraliyet',ex:'Royal family.',tr:'Krali'},
{word:'SOLID',type:'adj',def:'Sağlam, katı',ex:'Solid ground.',tr:'Katı'},
{word:'TUTOR',type:'noun',def:'Öğretmen, koç',ex:'A private tutor.',tr:'Koç'},
{word:'VIDEO',type:'noun',def:'Video',ex:'Watch a video.',tr:'Video'},
{word:'WIDER',type:'adj',def:'Daha geniş',ex:'A wider view.',tr:'Geniş'},
{word:'ALBUM',type:'noun',def:'Albüm',ex:'Photo album.',tr:'Albüm'},
{word:'BRAND',type:'noun',def:'Marka',ex:'A top brand.',tr:'Marka'},
{word:'COMIC',type:'noun',def:'Çizgi roman',ex:'Comic book.',tr:'Çizgi roman'},
{word:'DRILL',type:'noun',def:'Matkap, tatbikat',ex:'Fire drill.',tr:'Tatbikat'},
{word:'ELITE',type:'noun',def:'Seçkin, elit',ex:'The elite group.',tr:'Elit'},
{word:'FLOOD',type:'noun',def:'Sel',ex:'A flash flood.',tr:'Sel'},
{word:'LOGIC',type:'noun',def:'Mantık',ex:'Use logic.',tr:'Mantık'},
{word:'MOUSE',type:'noun',def:'Fare',ex:'Click the mouse.',tr:'Fare'},
{word:'OCEAN',type:'noun',def:'Okyanus',ex:'Pacific Ocean.',tr:'Okyanus'},
{word:'PEARL',type:'noun',def:'İnci',ex:'A pearl necklace.',tr:'İnci'},
{word:'QUEST',type:'noun',def:'Arayış',ex:'A quest for truth.',tr:'Arayış'},
{word:'REIGN',type:'noun',def:'Hükümdarlık',ex:'A long reign.',tr:'Saltanat'},
{word:'SHARK',type:'noun',def:'Köpek balığı',ex:'A great white.',tr:'Köpekbalığı'},
{word:'TRIBE',type:'noun',def:'Kabile',ex:'An ancient tribe.',tr:'Kabile'},
{word:'VIVID',type:'adj',def:'Canlı, parlak',ex:'Vivid colors.',tr:'Canlı'},
{word:'WITCH',type:'noun',def:'Cadı',ex:'A wicked witch.',tr:'Cadı'},
// 6-letter words (Medium)
{word:'BRIDGE',type:'noun',def:'Köprü',ex:'Cross the bridge.',tr:'Köprü'},
{word:'GROWTH',type:'noun',def:'Büyüme',ex:'Personal growth.',tr:'Büyüme'},
{word:'HUMBLE',type:'adj',def:'Alçakgönüllü',ex:'Stay humble.',tr:'Mütevazı'},
{word:'SIMPLE',type:'adj',def:'Basit',ex:'Keep it simple.',tr:'Basit'},
{word:'WONDER',type:'noun',def:'Hayranlık',ex:'I wonder why.',tr:'Merak'},
{word:'FLUENT',type:'adj',def:'Akıcı',ex:'Fluent in English.',tr:'Akıcı'},
{word:'ABSORB',type:'verb',def:'Emmek, özümsemek',ex:'Absorb knowledge.',tr:'Emmek'},
{word:'BANANA',type:'noun',def:'Muz',ex:'A ripe banana.',tr:'Muz'},
{word:'CANVAS',type:'noun',def:'Tuval',ex:'Paint on canvas.',tr:'Tuval'},
{word:'DINNER',type:'noun',def:'Akşam yemeği',ex:'Family dinner.',tr:'Akşam yemeği'},
{word:'ENABLE',type:'verb',def:'Etkinleştirmek',ex:'Enable the feature.',tr:'Etkinleştirmek'},
{word:'FILTER',type:'noun',def:'Filtre',ex:'Apply a filter.',tr:'Filtre'},
{word:'GENTLE',type:'adj',def:'Nazik, yumuşak',ex:'Be gentle.',tr:'Nazik'},
{word:'HORROR',type:'noun',def:'Korku',ex:'A horror movie.',tr:'Korku'},
{word:'INSECT',type:'noun',def:'Böcek',ex:'A tiny insect.',tr:'Böcek'},
{word:'JUNGLE',type:'noun',def:'Orman',ex:'Into the jungle.',tr:'Orman'},
{word:'KIDNEY',type:'noun',def:'Böbrek',ex:'Kidney function.',tr:'Böbrek'},
{word:'LAUNCH',type:'verb',def:'Başlatmak, fırlatmak',ex:'Launch the app.',tr:'Başlatmak'},
{word:'MIRROR',type:'noun',def:'Ayna',ex:'Look in the mirror.',tr:'Ayna'},
{word:'NATIVE',type:'adj',def:'Yerli, doğal',ex:'Native speaker.',tr:'Anadili'},
{word:'ORANGE',type:'noun',def:'Portakal',ex:'Orange juice.',tr:'Portakal'},
{word:'PLANET',type:'noun',def:'Gezegen',ex:'Our planet.',tr:'Gezegen'},
{word:'RANDOM',type:'adj',def:'Rastgele',ex:'A random choice.',tr:'Rastgele'},
{word:'SALARY',type:'noun',def:'Maaş',ex:'A good salary.',tr:'Maaş'},
{word:'TEMPLE',type:'noun',def:'Tapınak',ex:'An ancient temple.',tr:'Tapınak'},
{word:'UNIQUE',type:'adj',def:'Benzersiz',ex:'Truly unique.',tr:'Eşsiz'},
{word:'VALLEY',type:'noun',def:'Vadi',ex:'A green valley.',tr:'Vadi'},
{word:'WINDOW',type:'noun',def:'Pencere',ex:'Open the window.',tr:'Pencere'},
{word:'ANCHOR',type:'noun',def:'Çapa',ex:'Drop the anchor.',tr:'Çapa'},
{word:'BURNER',type:'noun',def:'Brülör',ex:'Back burner.',tr:'Ocak'},
{word:'CAUGHT',type:'verb',def:'Yakalandı',ex:'Caught in the act.',tr:'Yakalandı'},
{word:'DESIGN',type:'noun',def:'Tasarım',ex:'Good design.',tr:'Tasarım'},
{word:'ESCAPE',type:'verb',def:'Kaçmak',ex:'Escape reality.',tr:'Kaçış'},
{word:'FOREST',type:'noun',def:'Orman',ex:'A dense forest.',tr:'Orman'},
{word:'GUITAR',type:'noun',def:'Gitar',ex:'Play guitar.',tr:'Gitar'},
{word:'HONEST',type:'adj',def:'Dürüst',ex:'Be honest.',tr:'Dürüst'},
{word:'IMPORT',type:'verb',def:'İthal etmek',ex:'Import goods.',tr:'İthalat'},
{word:'LEGEND',type:'noun',def:'Efsane',ex:'A living legend.',tr:'Efsane'},
{word:'MANNER',type:'noun',def:'Tavır, tarz',ex:'Good manners.',tr:'Görgü'},
{word:'NARROW',type:'adj',def:'Dar',ex:'A narrow path.',tr:'Dar'},
{word:'POCKET',type:'noun',def:'Cep',ex:'In my pocket.',tr:'Cep'},
{word:'RESCUE',type:'verb',def:'Kurtarmak',ex:'Rescue mission.',tr:'Kurtarma'},
{word:'SPIRIT',type:'noun',def:'Ruh, moral',ex:'Team spirit.',tr:'Ruh'},
{word:'TICKET',type:'noun',def:'Bilet',ex:'Buy a ticket.',tr:'Bilet'},
{word:'VACUUM',type:'noun',def:'Vakum, boşluk',ex:'A vacuum cleaner.',tr:'Vakum'},
{word:'WEALTH',type:'noun',def:'Zenginlik',ex:'Great wealth.',tr:'Servet'},
{word:'ANIMAL',type:'noun',def:'Hayvan',ex:'A wild animal.',tr:'Hayvan'},
{word:'BATTLE',type:'noun',def:'Savaş',ex:'Win the battle.',tr:'Savaş'},
{word:'CARBON',type:'noun',def:'Karbon',ex:'Carbon footprint.',tr:'Karbon'},
{word:'DESERT',type:'noun',def:'Çöl',ex:'A vast desert.',tr:'Çöl'},
{word:'SAFETY',type:'noun',def:'Güvenlik',ex:'Safety first.',tr:'Güvenlik'},
{word:'TARGET',type:'noun',def:'Hedef',ex:'Hit the target.',tr:'Hedef'},
{word:'CASTLE',type:'noun',def:'Kale',ex:'An old castle.',tr:'Kale'},
{word:'FABRIC',type:'noun',def:'Kumaş',ex:'Soft fabric.',tr:'Kumaş'},
{word:'GARDEN',type:'noun',def:'Bahçe',ex:'A lovely garden.',tr:'Bahçe'},
{word:'HARBOR',type:'noun',def:'Liman',ex:'Safe harbor.',tr:'Liman'},
{word:'ISLAND',type:'noun',def:'Ada',ex:'A tropical island.',tr:'Ada'},
{word:'MARKER',type:'noun',def:'İşaretçi',ex:'A red marker.',tr:'Kalem'},
{word:'MOTION',type:'noun',def:'Hareket',ex:'Slow motion.',tr:'Hareket'},
{word:'NORMAL',type:'adj',def:'Normal',ex:'Perfectly normal.',tr:'Normal'},
{word:'PEPPER',type:'noun',def:'Biber',ex:'Black pepper.',tr:'Biber'},
{word:'RECIPE',type:'noun',def:'Tarif',ex:'A family recipe.',tr:'Tarif'},
{word:'SCREEN',type:'noun',def:'Ekran',ex:'Touch screen.',tr:'Ekran'},
{word:'TRIBAL',type:'adj',def:'Kabile',ex:'Tribal music.',tr:'Kabilevi'},
{word:'UPTURN',type:'noun',def:'Yükseliş',ex:'An upturn.',tr:'Yükselme'},
{word:'VERBAL',type:'adj',def:'Sözlü',ex:'Verbal warning.',tr:'Sözlü'},
// 7-letter words (Hard)
{word:'ACHIEVE',type:'verb',def:'Başarmak',ex:'Achieve your goals.',tr:'Başarmak',hard:true},
{word:'BREATHE',type:'verb',def:'Nefes almak',ex:'Breathe deeply.',tr:'Nefes almak',hard:true},
{word:'COURAGE',type:'noun',def:'Cesaret',ex:'Show courage.',tr:'Cesaret',hard:true},
{word:'IMAGINE',type:'verb',def:'Hayal etmek',ex:'Imagine the future.',tr:'Hayal etmek',hard:true},
{word:'INSPIRE',type:'verb',def:'İlham vermek',ex:'Inspire others.',tr:'İlham vermek',hard:true},
{word:'PASSION',type:'noun',def:'Tutku',ex:'Follow your passion.',tr:'Tutku',hard:true},
{word:'SUCCESS',type:'noun',def:'Başarı',ex:'Road to success.',tr:'Başarı',hard:true},
{word:'BALANCE',type:'noun',def:'Denge',ex:'Work-life balance.',tr:'Denge',hard:true},
{word:'CABINET',type:'noun',def:'Dolap, kabine',ex:'The cabinet.',tr:'Kabine',hard:true},
{word:'DEVELOP',type:'verb',def:'Geliştirmek',ex:'Develop skills.',tr:'Geliştirmek',hard:true},
{word:'EXAMINE',type:'verb',def:'İncelemek',ex:'Examine closely.',tr:'İncelemek',hard:true},
{word:'FORTUNE',type:'noun',def:'Servet, şans',ex:'Good fortune.',tr:'Talih',hard:true},
{word:'GENUINE',type:'adj',def:'Gerçek, samimi',ex:'Genuine smile.',tr:'Samimi',hard:true},
{word:'HABITAT',type:'noun',def:'Yaşam alanı',ex:'Natural habitat.',tr:'Yaşam alanı',hard:true},
{word:'IMPROVE',type:'verb',def:'İyileştirmek',ex:'Improve your English.',tr:'Geliştirmek',hard:true},
{word:'KITCHEN',type:'noun',def:'Mutfak',ex:'In the kitchen.',tr:'Mutfak',hard:true},
{word:'LOGICAL',type:'adj',def:'Mantıklı',ex:'A logical answer.',tr:'Mantıklı',hard:true},
{word:'MAXIMUM',type:'noun',def:'Maksimum',ex:'At maximum.',tr:'En fazla',hard:true},
{word:'NUCLEUS',type:'noun',def:'Çekirdek',ex:'The cell nucleus.',tr:'Çekirdek',hard:true},
{word:'OBVIOUS',type:'adj',def:'Açık, belli',ex:'It\'s obvious.',tr:'Bariz',hard:true},
{word:'PAINFUL',type:'adj',def:'Acı veren',ex:'A painful memory.',tr:'Acı verici',hard:true},
{word:'QUARTER',type:'noun',def:'Çeyrek',ex:'A quarter hour.',tr:'Çeyrek',hard:true},
{word:'RESERVE',type:'verb',def:'Ayırtmak',ex:'Reserve a seat.',tr:'Ayırtmak',hard:true},
{word:'SHELTER',type:'noun',def:'Barınak, sığınak',ex:'Find shelter.',tr:'Sığınak',hard:true},
{word:'TEACHER',type:'noun',def:'Öğretmen',ex:'A great teacher.',tr:'Öğretmen',hard:true},
{word:'VEHICLE',type:'noun',def:'Araç',ex:'A motor vehicle.',tr:'Araç',hard:true},
{word:'WEATHER',type:'noun',def:'Hava durumu',ex:'Nice weather.',tr:'Hava',hard:true},
{word:'ARRANGE',type:'verb',def:'Düzenlemek',ex:'Arrange a meeting.',tr:'Ayarlamak',hard:true},
{word:'BELIEVE',type:'verb',def:'İnanmak',ex:'Believe in yourself.',tr:'İnanmak',hard:true},
{word:'CAPTURE',type:'verb',def:'Yakalamak',ex:'Capture the moment.',tr:'Yakalamak',hard:true},
{word:'DIAMOND',type:'noun',def:'Elmas',ex:'A diamond ring.',tr:'Elmas',hard:true},
{word:'EMOTION',type:'noun',def:'Duygu',ex:'Strong emotion.',tr:'Duygu',hard:true},
{word:'FACTORY',type:'noun',def:'Fabrika',ex:'A car factory.',tr:'Fabrika',hard:true},
{word:'GATEWAY',type:'noun',def:'Giriş kapısı',ex:'The gateway.',tr:'Geçit',hard:true},
{word:'HARVEST',type:'noun',def:'Hasat',ex:'A rich harvest.',tr:'Hasat',hard:true},
{word:'KINGDOM',type:'noun',def:'Krallık',ex:'A vast kingdom.',tr:'Krallık',hard:true},
{word:'LEATHER',type:'noun',def:'Deri',ex:'Leather jacket.',tr:'Deri',hard:true},
{word:'MISSILE',type:'noun',def:'Füze',ex:'A guided missile.',tr:'Füze',hard:true},
{word:'OPINION',type:'noun',def:'Görüş, fikir',ex:'In my opinion.',tr:'Görüş',hard:true},
{word:'PATTERN',type:'noun',def:'Desen, kalıp',ex:'A clear pattern.',tr:'Kalıp',hard:true},
{word:'QUALITY',type:'noun',def:'Kalite',ex:'High quality.',tr:'Kalite',hard:true},
{word:'RELEASE',type:'verb',def:'Serbest bırakmak',ex:'Release the song.',tr:'Yayınlamak',hard:true},
{word:'STORAGE',type:'noun',def:'Depolama',ex:'Cloud storage.',tr:'Depolama',hard:true},
{word:'TRIUMPH',type:'noun',def:'Zafer',ex:'A great triumph.',tr:'Zafer',hard:true},
{word:'VOLCANO',type:'noun',def:'Yanardağ',ex:'Active volcano.',tr:'Yanardağ',hard:true},
{word:'ANCIENT',type:'adj',def:'Antik, eski',ex:'An ancient city.',tr:'Antik',hard:true},
{word:'BENEFIT',type:'noun',def:'Fayda',ex:'A great benefit.',tr:'Fayda',hard:true},
{word:'COMFORT',type:'noun',def:'Konfor, rahatlık',ex:'Total comfort.',tr:'Konfor',hard:true},
{word:'DISPLAY',type:'noun',def:'Ekran, sergi',ex:'On display.',tr:'Sergi',hard:true},
{word:'EXPLORE',type:'verb',def:'Keşfetmek',ex:'Explore the world.',tr:'Keşfetmek',hard:true},
{word:'FOREVER',type:'adv',def:'Sonsuza dek',ex:'Friends forever.',tr:'Sonsuza dek',hard:true},
{word:'HISTORY',type:'noun',def:'Tarih',ex:'Make history.',tr:'Tarih',hard:true},
{word:'JUSTICE',type:'noun',def:'Adalet',ex:'Seek justice.',tr:'Adalet',hard:true},
{word:'LIBERTY',type:'noun',def:'Özgürlük',ex:'Statue of Liberty.',tr:'Özgürlük',hard:true},
{word:'MYSTERY',type:'noun',def:'Gizem',ex:'A great mystery.',tr:'Gizem',hard:true},
{word:'NATURAL',type:'adj',def:'Doğal',ex:'Natural beauty.',tr:'Doğal',hard:true},
{word:'PREDICT',type:'verb',def:'Tahmin etmek',ex:'Hard to predict.',tr:'Tahmin',hard:true},
{word:'RADICAL',type:'adj',def:'Köklü, radikal',ex:'Radical change.',tr:'Köklü',hard:true},
{word:'SOCIETY',type:'noun',def:'Toplum',ex:'Modern society.',tr:'Toplum',hard:true},
{word:'TROUBLE',type:'noun',def:'Sorun, bela',ex:'In trouble.',tr:'Sorun',hard:true},
{word:'UNIFORM',type:'noun',def:'Üniforma',ex:'School uniform.',tr:'Üniforma',hard:true},
{word:'VERSION',type:'noun',def:'Sürüm, versiyon',ex:'Latest version.',tr:'Sürüm',hard:true},
{word:'WARRIOR',type:'noun',def:'Savaşçı',ex:'A brave warrior.',tr:'Savaşçı',hard:true},
];

// Word Connect puzzle data — verified crossword grids (no conflicts)
const WC_PUZZLES = [
{letters:'HEART',
 words:['ART','EAR','EAT','HER','ARE','HEAR','HEAT','TEAR','HEART'],
 defs:{ART:'Sanat',EAR:'Kulak',EAT:'Yemek',HER:'Onun (dişi)',ARE:'Olmak',HEAR:'Duymak',HEAT:'Isı',TEAR:'Yırtmak',HEART:'Kalp'},
 grid:[{word:'HEART',row:0,col:0,dir:'right'},{word:'ART',row:0,col:2,dir:'down'}],hint:'Kalp'},
{letters:'PLANT',
 words:['ANT','PAN','TAN','PAL','LAP','NAP','PLAN','PANT','PLANT'],
 defs:{ANT:'Karınca',PAN:'Tava',TAN:'Bronzlaşmak',PAL:'Arkadaş',LAP:'Kucak',NAP:'Şekerleme',PLAN:'Plan',PANT:'Nefes nefese kalmak',PLANT:'Bitki'},
 grid:[{word:'PLANT',row:0,col:0,dir:'right'},{word:'ANT',row:0,col:2,dir:'down'}],hint:'Bitki'},
{letters:'DREAM',
 words:['ARM','DAM','MAD','RED','ERA','READ','MADE','DARE','DEAR','DREAM'],
 defs:{ARM:'Kol',DAM:'Baraj',MAD:'Deli',RED:'Kırmızı',ERA:'Çağ',READ:'Okumak',MADE:'Yapıldı',DARE:'Cesaret etmek',DEAR:'Sevgili',DREAM:'Rüya'},
 grid:[{word:'DREAM',row:0,col:0,dir:'right'},{word:'ERA',row:0,col:2,dir:'down'}],hint:'Rüya'},
{letters:'STONE',
 words:['NOT','ONE','SET','TEN','TON','NET','NOTE','TONE','NOSE','STONE'],
 defs:{NOT:'Değil',ONE:'Bir',SET:'Ayarlamak',TEN:'On',TON:'Ton',NET:'Ağ',NOTE:'Not',TONE:'Ton',NOSE:'Burun',STONE:'Taş'},
 grid:[{word:'STONE',row:0,col:0,dir:'right'},{word:'ONE',row:0,col:2,dir:'down'}],hint:'Taş'},
{letters:'SMILE',
 words:['ELM','LIE','LIME','MILE','SLIM','SLIME','SMILE'],
 defs:{ELM:'Karaağaç',LIE:'Yalan',LIME:'Misket limonu',MILE:'Mil',SLIM:'İnce',SLIME:'Balçık',SMILE:'Gülümseme'},
 grid:[{word:'SMILE',row:0,col:0,dir:'right'},{word:'ILE',row:0,col:2,dir:'down'}],hint:'Gülümseme'},
{letters:'TRAIN',
 words:['AIR','ART','ANT','RAN','TAN','TIN','RAIN','TRAIN'],
 defs:{AIR:'Hava',ART:'Sanat',ANT:'Karınca',RAN:'Koştu',TAN:'Bronzlaşma',TIN:'Teneke',RAIN:'Yağmur',TRAIN:'Tren'},
 grid:[{word:'TRAIN',row:0,col:0,dir:'right'},{word:'AIR',row:0,col:2,dir:'down'}],hint:'Tren'},
{letters:'LEMON',
 words:['MEN','ONE','ELM','LONE','MOLE','MELON','LEMON'],
 defs:{MEN:'Erkekler',ONE:'Bir',ELM:'Karaağaç',LONE:'Yalnız',MOLE:'Köstebek',MELON:'Kavun',LEMON:'Limon'},
 grid:[{word:'LEMON',row:0,col:0,dir:'right'},{word:'MON',row:0,col:2,dir:'down'}],hint:'Limon'},
{letters:'TOWER',
 words:['OWE','ROW','TOW','TWO','WET','TOE','WORE','TORE','TOWER'],
 defs:{OWE:'Borçlu olmak',ROW:'Sıra',TOW:'Çekmek',TWO:'İki',WET:'Islak',TOE:'Ayak parmağı',WORE:'Giydi',TORE:'Yırttı',TOWER:'Kule'},
 grid:[{word:'TOWER',row:0,col:0,dir:'right'},{word:'WER',row:0,col:2,dir:'down'}],hint:'Kule'},
{letters:'BRAIN',
 words:['AIR','BAN','BAR','BIN','RAN','BARN','RAIN','BRAN','BRAIN'],
 defs:{AIR:'Hava',BAN:'Yasaklamak',BAR:'Çubuk',BIN:'Çöp kutusu',RAN:'Koştu',BARN:'Ahır',RAIN:'Yağmur',BRAN:'Kepek',BRAIN:'Beyin'},
 grid:[{word:'BRAIN',row:0,col:0,dir:'right'},{word:'AIN',row:0,col:2,dir:'down'}],hint:'Beyin'},
{letters:'FLAME',
 words:['ALE','ELF','ELM','FAME','LAME','LEAF','MALE','FLAME'],
 defs:{ALE:'Bira',ELF:'Cin',ELM:'Karaağaç',FAME:'Şöhret',LAME:'Topal',LEAF:'Yaprak',MALE:'Erkek',FLAME:'Alev'},
 grid:[{word:'FLAME',row:0,col:0,dir:'right'},{word:'AME',row:0,col:2,dir:'down'}],hint:'Alev'},
{letters:'LIGHT',
 words:['GIT','HIT','LIT','GILT','HILT','LIGHT'],
 defs:{GIT:'Git',HIT:'Vurmak',LIT:'Aydınlatılmış',GILT:'Altın yaldız',HILT:'Kabza',LIGHT:'Işık'},
 grid:[{word:'LIGHT',row:0,col:0,dir:'right'},{word:'GHT',row:0,col:2,dir:'down'}],hint:'Işık'},
{letters:'SPARK',
 words:['ARK','ASK','PAR','RAP','SAP','SPA','PARK','SPAR','SPARK'],
 defs:{ARK:'Gemi',ASK:'Sormak',PAR:'Eşit',RAP:'Rap',SAP:'Özsu',SPA:'Kaplıca',PARK:'Park',SPAR:'Boks yapmak',SPARK:'Kıvılcım'},
 grid:[{word:'SPARK',row:0,col:0,dir:'right'},{word:'ARK',row:0,col:2,dir:'down'}],hint:'Kıvılcım'},
{letters:'OCEAN',
 words:['ACE','CAN','CON','ONE','ACNE','CANE','CONE','ONCE','OCEAN'],
 defs:{ACE:'As',CAN:'Kutu',CON:'Dolandırmak',ONE:'Bir',ACNE:'Sivilce',CANE:'Baston',CONE:'Koni',ONCE:'Bir kez',OCEAN:'Okyanus'},
 grid:[{word:'OCEAN',row:0,col:0,dir:'right'},{word:'EAN',row:0,col:2,dir:'down'}],hint:'Okyanus'},
{letters:'CROWN',
 words:['CON','COW','COR','NOW','OWN','ROW','WON','CORN','WORN','CROWN'],
 defs:{CON:'Dolandırmak',COW:'İnek',COR:'Vay!',NOW:'Şimdi',OWN:'Sahip olmak',ROW:'Sıra',WON:'Kazandı',CORN:'Mısır',WORN:'Yıpranmış',CROWN:'Taç'},
 grid:[{word:'CROWN',row:0,col:0,dir:'right'},{word:'OWN',row:0,col:2,dir:'down'}],hint:'Taç'},
];

